apiVersion: v1
kind: ConfigMap
metadata:
  name: calculator
data:
  database_url: jdbc:postgresql://192.168.49.1:5432/job4j_devops?sslmode=disable
  database_username: postgres
  database_password: postgres